#!/bin/sh

PN=$(basename "$0")
VER='0.0.0'

if [ -s ~/.config/sbc/sbcrc ]
then
	username=$(grep 'username' ~/.config/sbc/sbcrc | cut -d ':' -f2)
	passwd=$(grep 'password' ~/.config/sbc/sbcrc | cut -d ':' -f2)
	domain=$(grep 'domain' ~/.config/sbc/sbcrc | cut -d ':' -f2-)
fi

usage () {
	echo >&2 "$PN - execute simple pastebin commands, $VER
usage: $PN [-h] [-l number] [-s pattern] [-o pattern] [-f file] ..." 
	exit 1
}

upload () {
	curl -u "${username?Username not provided}:${passwd?Password not provided}" "${domain?Domain not provided}"/upload -F file=@"$1"
}

list () {
	curl --silent -u "${username?Username not provided}:${passwd?Password not provided}" "${domain?Domain not provided}"/bin/ | tail -"$(($1+1))" | head -"$1" | sed 's/<[^>]*>//g' 
}

download () {
	curl --silent -u "${username?Username not provided}:${passwd?Password not provided}" "${domain?Domain not provided}"/bin/"$1" > "${1##*_}" 
}

search () {
	curl --silent -u "${username?Username not provided}:${passwd?Password not provided}" "${domain?Domain not provided}"/bin/ | grep -i "$1" | sed 's/<[^>]*>//g'
}

geturl () {
	curl --silent -u "${username?Username not provided}:${passwd?Password not provided}" "${domain? Domain not provided}"/bin/ | grep -i "$1" | cut -d '>' -f1 | cut -d '=' -f2 | cut -b 2- | rev | cut -b 2- | rev  
}

while getopts "hl:s:f:o:" option; do
	case $option in 
		h) # Display usage
			usage
			;;
		l) # List a number of files
			list $2
			;;
		s) # Search for files matching a pattern
			search $2
			;;
		f) # Upload a file in the current directory to the pastebin
			upload $2
			;;
		o) # Download ALL files matching a pattern
		 	search $2 | while read line; do download $(geturl $line); done 		
			;;
		\?) # Invalid option
			echo "Error: Invalid option."
			usage
			;;
	esac
done
